<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">

  <name>mrs_core_examples</name>

  <version>2.0.0</version>
  <description>MRS Core Examples</description>

  <author email="tomas.baca@fel.cvut.cz">Tomas Baca</author>
  <maintainer email="tomas.baca@fel.cvut.cz">Tomas Baca</maintainer>

  <license>BSD-3</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>example_controller_plugin</depend>
  <depend>example_estimator_plugin</depend>
  <depend>example_tracker_plugin</depend>
  <depend>example_plugin_manager</depend>
  <depend>example_plugins</depend>
  <depend>example_waypoint_flier</depend>
  <depend>example_waypoint_flier_native</depend>
  <depend>example_sweeping_generator</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
